version: "3.9"

services:

  db:
    image: chandrikadevops/cloud:dbimage
    deploy:
      replicas: 1   # IMPORTANT (not 3)

  auth_service:
    image: chandrikadevops/cloud:authimage
    deploy:
      replicas: 3

  book_service:
    image: chandrikadevops/cloud:bookimage
    deploy:
      replicas: 3

  borrow_service:
    image: chandrikadevops/cloud:borrowimage
    deploy:
      replicas: 3

  app_service:
    image: chandrikadevops/cloud:appimage
    ports:
      - "5000:5000"   # ONLY this should have port
    deploy:
      replicas: 3
